/*****************************************************************************/
/* GlobalWeaponAndBulletInfo.h                                               */
/* Written by Daniel Schroeder                                               */
/* Created on July 15, 2005                                                  */
/* Last Updated July 26, 2005                                                */
/*---------------------------------------------------------------------------*/
/*   This file specifies all of the global data pertaining to Weapons and    */
/* Bullets, such as how much damage they inflict, the speed they should      */
/* travel, and any other Weapon or Bullet related information.               */
/*****************************************************************************/

#ifndef GLOBAL_WEAPON_AND_BULLET_INFO_H
#define GLOBAL_WEAPON_AND_BULLET_INFO_H

// ********* Weapon/Bullet Detonation Causes **********

// Types of Detonation Causes
const int GiDETONATE_ON_CONTACT				= 0;
const int GiDETONATE_ON_KEYPRESS_OR_CONTACT	= 1;
const int GiDETONATE_WHEN_OFF_SCREEN		= 2;
const int GiDETONATE_ON_TIMER				= 3;
const int GiDETONATE_ON_KEY_PRESS			= 4;


//********** Weapons and Bullets ID's, Speeds, Damage amounts, Durations, and Delays **********

// Total Number of Weapons/Bullets in the game
const int GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME			= 15;

// General Weapon Types
const int GiNATIVE_WEAPON							= 0;
const int GiFOREIGN_WEAPON							= 1;

// Weapon ID's (Specific Types)
const int GiNORMAL_WEAPON							= 0;
const int GiTHREE_NORMAL_WEAPON						= 1;
const int GiMACHINE_GUN_WEAPON						= 2;	// Shoots very fast
const int GiTHREE_MACHINE_GUN_WEAPON				= 3;
const int GiFLAME_THROWER_WEAPON					= 4;	// Only travels so far
const int GiFIREBALL_WEAPON							= 5;
const int GiLASER_WEAPON							= 6;	// Passes through enemy
const int GiBOMB_WEAPON								= 7;	// Large radius. Explodes on contact or when detonate is pressed
const int GiRAM_WEAPON								= 8;
const int GiBUBBLE_WEAPON							= 9;	// Prevents enemy from shooting
const int GiHEAT_SEEK_WEAPON						= 10;	// Heatseeking missile
const int GiMISSILE_WEAPON							= 11;
const int GiSONIC_WAVE_WEAPON						= 12;	// Spreads out
const int GiEMP_WEAPON								= 13;	// Disables all enemy ships temporarily
const int GiCLUSTER_BOMB_WEAPON						= 14;	// Fires 40 small bombs grouped together as 1, press button and it spreads into 4 groups of 10, press again and all 40 bombs spread out


// Bullet ID's (Specific Types)
const int GiNORMAL_GUN_BULLET						= GiNORMAL_WEAPON;
const int GiTHREE_NORMAL_GUN_BULLET					= GiTHREE_NORMAL_WEAPON;
const int GiMACHINE_GUN_BULLET						= GiMACHINE_GUN_WEAPON;
const int GiTHREE_MACHINE_GUN_BULLET				= GiTHREE_MACHINE_GUN_WEAPON;
const int GiFLAME_THROWER_BULLET					= GiFLAME_THROWER_WEAPON;
const int GiFIREBALL_BULLET							= GiFIREBALL_WEAPON;
const int GiLASER_BULLET							= GiLASER_WEAPON;
const int GiBOMB_BULLET								= GiBOMB_WEAPON;
const int GiRAM_BULLET								= GiRAM_WEAPON;
const int GiBUBBLE_BULLET							= GiBUBBLE_WEAPON;
const int GiHEAT_SEEK_BULLET						= GiHEAT_SEEK_WEAPON;
const int GiMISSILE_BULLET							= GiMISSILE_WEAPON;
const int GiSONIC_WAVE_BULLET						= GiSONIC_WAVE_WEAPON;
const int GiEMP_BULLET								= GiEMP_WEAPON;
const int GiCLUSTER_BOMB_BULLET						= GiCLUSTER_BOMB_WEAPON;


// Bullet General Types
const int GiNORMAL_GUN_BULLET_GENERAL_TYPE			= GiNATIVE_WEAPON;
const int GiTHREE_NORMAL_GUN_BULLET_GENERAL_TYPE	= GiNATIVE_WEAPON;			
const int GiMACHINE_GUN_BULLET_GENERAL_TYPE			= GiNATIVE_WEAPON;
const int GiTHREE_MACHINE_GUN_BULLET_GENERAL_TYPE	= GiNATIVE_WEAPON;
const int GiFLAME_THROWER_BULLET_GENERAL_TYPE		= GiFOREIGN_WEAPON;
const int GiFIREBALL_BULLET_GENERAL_TYPE			= GiFOREIGN_WEAPON;
const int GiLASER_BULLET_GENERAL_TYPE				= GiFOREIGN_WEAPON;
const int GiBOMB_BULLET_GENERAL_TYPE				= GiFOREIGN_WEAPON;
const int GiRAM_BULLET_GENERAL_TYPE					= GiFOREIGN_WEAPON;
const int GiBUBBLE_BULLET_GENERAL_TYPE				= GiFOREIGN_WEAPON;
const int GiHEAT_SEEK_BULLET_GENERAL_TYPE			= GiFOREIGN_WEAPON;
const int GiMISSILE_BULLET_GENERAL_TYPE				= GiFOREIGN_WEAPON;
const int GiSONIC_WAVE_BULLET_GENERAL_TYPE			= GiFOREIGN_WEAPON;
const int GiEMP_BULLET_GENERAL_TYPE					= GiFOREIGN_WEAPON;
const int GiCLUSTER_BOMB_BULLET_GENERAL_TYPE		= GiFOREIGN_WEAPON;


// Bullet X and Y Velocities
const int GiNORMAL_GUN_BULLET_X_VELOCITY			= 0;	
const int GiNORMAL_GUN_BULLET_Y_VELOCITY			= -400;
const int GiTHREE_NORMAL_GUN_BULLET_X_VELOCITY		= 0;	
const int GiTHREE_NORMAL_GUN_BULLET_Y_VELOCITY		= -400;	
const int GiMACHINE_GUN_BULLET_X_VELOCITY			= 0;
const int GiMACHINE_GUN_BULLET_Y_VELOCITY			= -600;
const int GiTHREE_MACHINE_GUN_BULLET_X_VELOCITY		= 0;
const int GiTHREE_MACHINE_GUN_BULLET_Y_VELOCITY		= -600;	
const int GiFLAME_THROWER_BULLET_X_VELOCITY			= 0;
const int GiFLAME_THROWER_BULLET_Y_VELOCITY			= -300;	
const int GiFIREBALL_BULLET_X_VELOCITY				= 0;
const int GiFIREBALL_BULLET_Y_VELOCITY				= -300;							
const int GiLASER_BULLET_X_VELOCITY					= 0;
const int GiLASER_BULLET_Y_VELOCITY					= -700;		
const int GiBOMB_BULLET_X_VELOCITY					= 0;
const int GiBOMB_BULLET_Y_VELOCITY					= -250;		
const int GiRAM_BULLET_X_VELOCITY					= 0;
const int GiRAM_BULLET_Y_VELOCITY					= -10;
const int GiBUBBLE_BULLET_X_VELOCITY				= 0;
const int GiBUBBLE_BULLET_Y_VELOCITY				= -5;	
const int GiHEAT_SEEK_BULLET_X_VELOCITY				= 0;
const int GiHEAT_SEEK_BULLET_Y_VELOCITY				= -6;		
const int GiMISSILE_BULLET_X_VELOCITY				= 0;
const int GiMISSILE_BULLET_Y_VELOCITY				= -8;		
const int GiSONIC_WAVE_BULLET_X_VELOCITY			= 0;
const int GiSONIC_WAVE_BULLET_Y_VELOCITY			= -7;	
const int GiEMP_BULLET_X_VELOCITY					= 0;
const int GiEMP_BULLET_Y_VELOCITY					= 0;	// 0 because it hits everybody on screen		
const int GiCLUSTER_BOMB_BULLET_X_VELOCITY			= 0;
const int GiCLUSTER_BOMB_BULLET_Y_VELOCITY			= -5;		


// Bullets Detonation X and Y Velocities
const int GiNORMAL_GUN_BULLET_DETONATION_X_VELOCITY			= 0;	
const int GiNORMAL_GUN_BULLET_DETONATION_Y_VELOCITY			= 0;
const int GiTHREE_NORMAL_GUN_BULLET_DETONATION_X_VELOCITY	= 0;	
const int GiTHREE_NORMAL_GUN_BULLET_DETONATION_Y_VELOCITY	= 0;
const int GiMACHINE_GUN_BULLET_DETONATION_X_VELOCITY		= 0;
const int GiMACHINE_GUN_BULLET_DETONATION_Y_VELOCITY		= 0;
const int GiTHREE_MACHINE_GUN_BULLET_DETONATION_X_VELOCITY	= 0;
const int GiTHREE_MACHINE_GUN_BULLET_DETONATION_Y_VELOCITY	= 0;
const int GiFLAME_THROWER_BULLET_DETONATION_X_VELOCITY		= 0;
const int GiFLAME_THROWER_BULLET_DETONATION_Y_VELOCITY		= 0;	
const int GiFIREBALL_BULLET_DETONATION_X_VELOCITY			= 0;
const int GiFIREBALL_BULLET_DETONATION_Y_VELOCITY			= -75;							
const int GiLASER_BULLET_DETONATION_X_VELOCITY				= 0;
const int GiLASER_BULLET_DETONATION_Y_VELOCITY				= 0;		
const int GiBOMB_BULLET_DETONATION_X_VELOCITY				= 0;
const int GiBOMB_BULLET_DETONATION_Y_VELOCITY				= 0;		
const int GiRAM_BULLET_DETONATION_X_VELOCITY				= 0;
const int GiRAM_BULLET_DETONATION_Y_VELOCITY				= 0;
const int GiBUBBLE_BULLET_DETONATION_X_VELOCITY				= 0;
const int GiBUBBLE_BULLET_DETONATION_Y_VELOCITY				= 0;	
const int GiHEAT_SEEK_BULLET_DETONATION_X_VELOCITY			= 0;
const int GiHEAT_SEEK_BULLET_DETONATION_Y_VELOCITY			= 0;		
const int GiMISSILE_BULLET_DETONATION_X_VELOCITY			= 0;
const int GiMISSILE_BULLET_DETONATION_Y_VELOCITY			= 0;		
const int GiSONIC_WAVE_BULLET_DETONATION_X_VELOCITY			= 0;
const int GiSONIC_WAVE_BULLET_DETONATION_Y_VELOCITY			= 0;	
const int GiEMP_BULLET_DETONATION_X_VELOCITY				= 0;
const int GiEMP_BULLET_DETONATION_Y_VELOCITY				= 0;
const int GiCLUSTER_BOMB_BULLET_DETONATION_X_VELOCITY		= 0;
const int GiCLUSTER_BOMB_BULLET_DETONATION_Y_VELOCITY		= 0;	


// These are base damages, they may have a small random damage added to them for the total damage
const int GiNORMAL_GUN_BULLET_BASE_DAMAGE			= 5;	
const int GiTHREE_NORMAL_GUN_BULLET_BASE_DAMAGE		= 5;	
const int GiMACHINE_GUN_BULLET_BASE_DAMAGE			= 2;	
const int GiTHREE_MACHINE_GUN_BULLET_BASE_DAMAGE	= 2;	
const int GiFLAME_THROWER_BULLET_BASE_DAMAGE		= 5;	
const int GiFIREBALL_BULLET_BASE_DAMAGE				= 30;	
const int GiLASER_BULLET_BASE_DAMAGE				= 7;	
const int GiBOMB_BULLET_BASE_DAMAGE					= 40;	
const int GiRAM_BULLET_BASE_DAMAGE					= 40;	
const int GiBUBBLE_BULLET_BASE_DAMAGE				= 0;	
const int GiHEAT_SEEK_BULLET_BASE_DAMAGE			= 10;	
const int GiMISSILE_BULLET_BASE_DAMAGE				= 20;	
const int GiSONIC_WAVE_BULLET_BASE_DAMAGE			= 7;	
const int GiEMP_BULLET_BASE_DAMAGE					= 0;	
const int GiCLUSTER_BOMB_BULLET_BASE_DAMAGE			= 4;	// per each of the 40 fired

// These are random damages that are added to the base damages (Random Damage of 5 means 0,1,2,3, or 4 may be added to the Base Damage)
const int GiNORMAL_GUN_BULLET_RANDOM_DAMAGE			= 3;
const int GiTHREE_NORMAL_GUN_BULLET_RANDOM_DAMAGE	= 3;
const int GiMACHINE_GUN_BULLET_RANDOM_DAMAGE		= 1;
const int GiTHREE_MACHINE_GUN_BULLET_RANDOM_DAMAGE	= 1;
const int GiFLAME_THROWER_BULLET_RANDOM_DAMAGE		= 3;
const int GiFIREBALL_BULLET_RANDOM_DAMAGE			= 10;
const int GiLASER_BULLET_RANDOM_DAMAGE				= 3;
const int GiBOMB_BULLET_RANDOM_DAMAGE				= 15;
const int GiRAM_BULLET_RANDOM_DAMAGE				= 8;
const int GiBUBBLE_BULLET_RANDOM_DAMAGE				= 0;
const int GiHEAT_SEEK_BULLET_RANDOM_DAMAGE			= 5;
const int GiMISSILE_BULLET_RANDOM_DAMAGE			= 5;
const int GiSONIC_WAVE_BULLET_RANDOM_DAMAGE			= 5;
const int GiEMP_BULLET_RANDOM_DAMAGE				= 0;
const int GiCLUSTER_BOMB_BULLET_RANDOM_DAMAGE		= 2;	// per each of the 40 fired


// Mark if Bullets have Alternate Effects or require special processing
const bool GiNORMAL_GUN_BULLET_HAS_ALTERNATE_EFFECT				= false;
const bool GiTHREE_NORMAL_GUN_BULLET_HAS_ALTERNATE_EFFECT		= true;
const bool GiMACHINE_GUN_BULLET_HAS_ALTERNATE_EFFECT			= false;
const bool GiTHREE_MACHINE_GUN_BULLET_HAS_ALTERNATE_EFFECT		= true;
const bool GiFLAME_THROWER_BULLET_HAS_ALTERNATE_EFFECT			= false;
const bool GiFIREBALL_BULLET_HAS_ALTERNATE_EFFECT				= false;
const bool GiLASER_BULLET_HAS_ALTERNATE_EFFECT					= false;
const bool GiBOMB_BULLET_HAS_ALTERNATE_EFFECT					= false;
const bool GiRAM_BULLET_HAS_ALTERNATE_EFFECT					= false;
const bool GiBUBBLE_BULLET_HAS_ALTERNATE_EFFECT					= true;	// Disable ship for 10 seconds
const bool GiHEAT_SEEK_BULLET_HAS_ALTERNATE_EFFECT				= false;
const bool GiMISSILE_BULLET_HAS_ALTERNATE_EFFECT				= false;
const bool GiSONIC_WAVE_BULLET_HAS_ALTERNATE_EFFECT				= false;
const bool GiEMP_BULLET_HAS_ALTERNATE_EFFECT					= true;	// Disable all ships for 7 seconds
const bool GiCLUSTER_BOMB_BULLET_HAS_ALTERNATE_EFFECT			= false;


// Durations of weapons that have effects other than damage
const int GiNORMAL_GUN_BULLET_DURATION				= 0;
const int GiTHREE_NORMAL_GUN_BULLET_DURATION		= 0;
const int GiMACHINE_GUN_BULLET_DURATION				= 0;
const int GiTHREE_MACHINE_GUN_BULLET_DURATION		= 0;
const int GiFLAME_THROWER_BULLET_DURATION			= 0;
const int GiFIREBALL_BULLET_DURATION				= 0;
const int GiLASER_BULLET_DURATION					= 0;
const int GiBOMB_BULLET_DURATION					= 0;
const int GiRAM_BULLET_DURATION						= 0;
const int GiBUBBLE_BULLET_DURATION					= 1000;	// Disable ship for 10 seconds
const int GiHEAT_SEEK_BULLET_DURATION				= 0;
const int GiMISSILE_BULLET_DURATION					= 0;
const int GiSONIC_WAVE_BULLET_DURATION				= 0;
const int GiEMP_BULLET_DURATION						= 7000;	// Disable all ships for 7 seconds
const int GiCLUSTER_BOMB_BULLET_DURATION			= 0;


// Bullets Cause of Detonation
const int GiNORMAL_GUN_BULLET_CAUSE_OF_DETONATION			= GiDETONATE_ON_CONTACT;
const int GiTHREE_NORMAL_GUN_BULLET_CAUSE_OF_DETONATION		= GiDETONATE_ON_CONTACT;
const int GiMACHINE_GUN_BULLET_CAUSE_OF_DETONATION			= GiDETONATE_ON_CONTACT;
const int GiTHREE_MACHINE_GUN_BULLET_CAUSE_OF_DETONATION	= GiDETONATE_ON_CONTACT;
const int GiFLAME_THROWER_BULLET_CAUSE_OF_DETONATION		= GiDETONATE_ON_CONTACT;
const int GiFIREBALL_BULLET_CAUSE_OF_DETONATION				= GiDETONATE_ON_CONTACT;
const int GiLASER_BULLET_CAUSE_OF_DETONATION				= GiDETONATE_WHEN_OFF_SCREEN;
const int GiBOMB_BULLET_CAUSE_OF_DETONATION					= GiDETONATE_ON_KEYPRESS_OR_CONTACT;
const int GiRAM_BULLET_CAUSE_OF_DETONATION					= GiDETONATE_ON_CONTACT;
const int GiBUBBLE_BULLET_CAUSE_OF_DETONATION				= GiDETONATE_ON_CONTACT;
const int GiHEAT_SEEK_BULLET_CAUSE_OF_DETONATION			= GiDETONATE_ON_CONTACT;
const int GiMISSILE_BULLET_CAUSE_OF_DETONATION				= GiDETONATE_ON_CONTACT;
const int GiSONIC_WAVE_BULLET_CAUSE_OF_DETONATION			= GiDETONATE_ON_CONTACT;
const int GiEMP_BULLET_CAUSE_OF_DETONATION					= GiDETONATE_ON_CONTACT;
const int GiCLUSTER_BOMB_BULLET_CAUSE_OF_DETONATION			= GiDETONATE_ON_TIMER;


// Delay before same Weapon can be fired again (1000 = 1 second)
const int GiNORMAL_WEAPON_DELAY						= 350;
const int GiTHREE_NORMAL_WEAPON_DELAY				= 350;
const int GiMACHINE_GUN_WEAPON_DELAY				= 100;	
const int GiTHREE_MACHINE_GUN_WEAPON_DELAY			= 100;
const int GiFLAME_THROWER_WEAPON_DELAY				= 50;	
const int GiFIREBALL_WEAPON_DELAY					= 400;
const int GiLASER_WEAPON_DELAY						= 250;
const int GiBOMB_WEAPON_DELAY						= 350;
const int GiRAM_WEAPON_DELAY						= 1000;
const int GiBUBBLE_WEAPON_DELAY						= 350;
const int GiHEAT_SEEK_WEAPON_DELAY					= 350;
const int GiMISSILE_WEAPON_DELAY					= 350;
const int GiSONIC_WAVE_WEAPON_DELAY					= 1000;
const int GiEMP_WEAPON_DELAY						= 5000;
const int GiCLUSTER_BOMB_WEAPON_DELAY				= 500;

const int GiCHANGE_WEAPON_DELAY						= 300;
const int GiDETONATE_WEAPON_DELAY					= 200;


//********** Bullet Information Arrays **********

// The array contents must stay in the same order as the Bullet ID's
// Used to create the Bullet Model information in a loop

// Bullets General Types
const int GiBULLET_GENERAL_TYPES[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_GENERAL_TYPE, GiTHREE_NORMAL_GUN_BULLET_GENERAL_TYPE, 
 GiMACHINE_GUN_BULLET_GENERAL_TYPE, GiTHREE_MACHINE_GUN_BULLET_GENERAL_TYPE,
 GiFLAME_THROWER_BULLET_GENERAL_TYPE, GiFIREBALL_BULLET_GENERAL_TYPE,
 GiLASER_BULLET_GENERAL_TYPE, GiBOMB_BULLET_GENERAL_TYPE,
 GiRAM_BULLET_GENERAL_TYPE, GiBUBBLE_BULLET_GENERAL_TYPE,
 GiHEAT_SEEK_BULLET_GENERAL_TYPE, GiMISSILE_BULLET_GENERAL_TYPE,
 GiSONIC_WAVE_BULLET_GENERAL_TYPE, GiEMP_BULLET_GENERAL_TYPE,
 GiCLUSTER_BOMB_BULLET_GENERAL_TYPE};

// Bullets X Velocities
const int GiBULLET_X_VELOCITY[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_X_VELOCITY, GiTHREE_NORMAL_GUN_BULLET_X_VELOCITY, 
 GiMACHINE_GUN_BULLET_X_VELOCITY, GiTHREE_MACHINE_GUN_BULLET_X_VELOCITY,
 GiFLAME_THROWER_BULLET_X_VELOCITY, GiFIREBALL_BULLET_X_VELOCITY,
 GiLASER_BULLET_X_VELOCITY, GiBOMB_BULLET_X_VELOCITY,
 GiRAM_BULLET_X_VELOCITY, GiBUBBLE_BULLET_X_VELOCITY,
 GiHEAT_SEEK_BULLET_X_VELOCITY, GiMISSILE_BULLET_X_VELOCITY,
 GiSONIC_WAVE_BULLET_X_VELOCITY, GiEMP_BULLET_X_VELOCITY,
 GiCLUSTER_BOMB_BULLET_X_VELOCITY};

// Bullets Y Velocities
const int GiBULLET_Y_VELOCITY[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_Y_VELOCITY, GiTHREE_NORMAL_GUN_BULLET_Y_VELOCITY,
 GiMACHINE_GUN_BULLET_Y_VELOCITY, GiTHREE_MACHINE_GUN_BULLET_Y_VELOCITY,
 GiFLAME_THROWER_BULLET_Y_VELOCITY, GiFIREBALL_BULLET_Y_VELOCITY,
 GiLASER_BULLET_Y_VELOCITY, GiBOMB_BULLET_Y_VELOCITY,
 GiRAM_BULLET_Y_VELOCITY, GiBUBBLE_BULLET_Y_VELOCITY,
 GiHEAT_SEEK_BULLET_Y_VELOCITY, GiMISSILE_BULLET_Y_VELOCITY,
 GiSONIC_WAVE_BULLET_Y_VELOCITY, GiEMP_BULLET_Y_VELOCITY,
 GiCLUSTER_BOMB_BULLET_Y_VELOCITY};

// Bullets Detonation X Velocities
const int GiBULLET_DETONATION_X_VELOCITY[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_DETONATION_X_VELOCITY, GiTHREE_NORMAL_GUN_BULLET_DETONATION_X_VELOCITY, 
 GiMACHINE_GUN_BULLET_DETONATION_X_VELOCITY, GiTHREE_MACHINE_GUN_BULLET_DETONATION_X_VELOCITY,
 GiFLAME_THROWER_BULLET_DETONATION_X_VELOCITY, GiFIREBALL_BULLET_DETONATION_X_VELOCITY,
 GiLASER_BULLET_DETONATION_X_VELOCITY, GiBOMB_BULLET_DETONATION_X_VELOCITY,
 GiRAM_BULLET_DETONATION_X_VELOCITY, GiBUBBLE_BULLET_DETONATION_X_VELOCITY,
 GiHEAT_SEEK_BULLET_DETONATION_X_VELOCITY, GiMISSILE_BULLET_DETONATION_X_VELOCITY,
 GiSONIC_WAVE_BULLET_DETONATION_X_VELOCITY, GiEMP_BULLET_DETONATION_X_VELOCITY,
 GiCLUSTER_BOMB_BULLET_DETONATION_X_VELOCITY};

// Bullets Detonation Y Velocities
const int GiBULLET_DETONATION_Y_VELOCITY[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_DETONATION_Y_VELOCITY, GiTHREE_NORMAL_GUN_BULLET_DETONATION_Y_VELOCITY,
 GiMACHINE_GUN_BULLET_DETONATION_Y_VELOCITY, GiTHREE_MACHINE_GUN_BULLET_DETONATION_Y_VELOCITY,
 GiFLAME_THROWER_BULLET_DETONATION_Y_VELOCITY, GiFIREBALL_BULLET_DETONATION_Y_VELOCITY,
 GiLASER_BULLET_DETONATION_Y_VELOCITY, GiBOMB_BULLET_DETONATION_Y_VELOCITY,
 GiRAM_BULLET_DETONATION_Y_VELOCITY, GiBUBBLE_BULLET_DETONATION_Y_VELOCITY,
 GiHEAT_SEEK_BULLET_DETONATION_Y_VELOCITY, GiMISSILE_BULLET_DETONATION_Y_VELOCITY,
 GiSONIC_WAVE_BULLET_DETONATION_Y_VELOCITY, GiEMP_BULLET_DETONATION_Y_VELOCITY,
 GiCLUSTER_BOMB_BULLET_DETONATION_Y_VELOCITY};

// Bullets Base Damages
const int GiBULLET_BASE_DAMAGE[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_BASE_DAMAGE, GiTHREE_NORMAL_GUN_BULLET_BASE_DAMAGE,
 GiMACHINE_GUN_BULLET_BASE_DAMAGE, GiTHREE_MACHINE_GUN_BULLET_BASE_DAMAGE,
 GiFLAME_THROWER_BULLET_BASE_DAMAGE, GiFIREBALL_BULLET_BASE_DAMAGE,
 GiLASER_BULLET_BASE_DAMAGE, GiBOMB_BULLET_BASE_DAMAGE,
 GiRAM_BULLET_BASE_DAMAGE, GiBUBBLE_BULLET_BASE_DAMAGE,
 GiHEAT_SEEK_BULLET_BASE_DAMAGE, GiMISSILE_BULLET_BASE_DAMAGE,
 GiSONIC_WAVE_BULLET_BASE_DAMAGE, GiEMP_BULLET_BASE_DAMAGE,
 GiCLUSTER_BOMB_BULLET_BASE_DAMAGE};

// Bullets Random Damages
const int GiBULLET_RANDOM_DAMAGE[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_RANDOM_DAMAGE, GiTHREE_NORMAL_GUN_BULLET_RANDOM_DAMAGE, 
 GiMACHINE_GUN_BULLET_RANDOM_DAMAGE, GiTHREE_MACHINE_GUN_BULLET_RANDOM_DAMAGE,
 GiFLAME_THROWER_BULLET_RANDOM_DAMAGE, GiFIREBALL_BULLET_RANDOM_DAMAGE,
 GiLASER_BULLET_RANDOM_DAMAGE, GiBOMB_BULLET_RANDOM_DAMAGE,
 GiRAM_BULLET_RANDOM_DAMAGE, GiBUBBLE_BULLET_RANDOM_DAMAGE,
 GiHEAT_SEEK_BULLET_RANDOM_DAMAGE, GiMISSILE_BULLET_RANDOM_DAMAGE,
 GiSONIC_WAVE_BULLET_RANDOM_DAMAGE, GiEMP_BULLET_RANDOM_DAMAGE,
 GiCLUSTER_BOMB_BULLET_RANDOM_DAMAGE};

// Bullet Alternate Effects
const bool GiBULLET_HAS_ALTERNATE_EFFECT[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_HAS_ALTERNATE_EFFECT, GiTHREE_NORMAL_GUN_BULLET_HAS_ALTERNATE_EFFECT,
 GiMACHINE_GUN_BULLET_HAS_ALTERNATE_EFFECT, GiTHREE_MACHINE_GUN_BULLET_HAS_ALTERNATE_EFFECT,
 GiFLAME_THROWER_BULLET_HAS_ALTERNATE_EFFECT, GiFIREBALL_BULLET_HAS_ALTERNATE_EFFECT,
 GiLASER_BULLET_HAS_ALTERNATE_EFFECT, GiBOMB_BULLET_HAS_ALTERNATE_EFFECT,
 GiRAM_BULLET_HAS_ALTERNATE_EFFECT, GiBUBBLE_BULLET_HAS_ALTERNATE_EFFECT,
 GiHEAT_SEEK_BULLET_HAS_ALTERNATE_EFFECT, GiMISSILE_BULLET_HAS_ALTERNATE_EFFECT,
 GiSONIC_WAVE_BULLET_HAS_ALTERNATE_EFFECT, GiEMP_BULLET_HAS_ALTERNATE_EFFECT,
 GiCLUSTER_BOMB_BULLET_HAS_ALTERNATE_EFFECT};

// Bullet Durations
const int GiBULLET_DURATION[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_DURATION, GiTHREE_NORMAL_GUN_BULLET_DURATION,
 GiMACHINE_GUN_BULLET_DURATION, GiTHREE_MACHINE_GUN_BULLET_DURATION,
 GiFLAME_THROWER_BULLET_DURATION, GiFIREBALL_BULLET_DURATION,
 GiLASER_BULLET_DURATION, GiBOMB_BULLET_DURATION,
 GiRAM_BULLET_DURATION, GiBUBBLE_BULLET_DURATION,
 GiHEAT_SEEK_BULLET_DURATION, GiMISSILE_BULLET_DURATION,
 GiSONIC_WAVE_BULLET_DURATION, GiEMP_BULLET_DURATION,
 GiCLUSTER_BOMB_BULLET_DURATION};

// Bullet Cause of Detonations
const int GiBULLET_CAUSE_OF_DETONATION[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_GUN_BULLET_CAUSE_OF_DETONATION, GiTHREE_NORMAL_GUN_BULLET_CAUSE_OF_DETONATION,
 GiMACHINE_GUN_BULLET_CAUSE_OF_DETONATION, GiTHREE_MACHINE_GUN_BULLET_CAUSE_OF_DETONATION,
 GiFLAME_THROWER_BULLET_CAUSE_OF_DETONATION, GiFIREBALL_BULLET_CAUSE_OF_DETONATION,
 GiLASER_BULLET_CAUSE_OF_DETONATION, GiBOMB_BULLET_CAUSE_OF_DETONATION,
 GiRAM_BULLET_CAUSE_OF_DETONATION, GiBUBBLE_BULLET_CAUSE_OF_DETONATION,
 GiHEAT_SEEK_BULLET_CAUSE_OF_DETONATION, GiMISSILE_BULLET_CAUSE_OF_DETONATION,
 GiSONIC_WAVE_BULLET_CAUSE_OF_DETONATION, GiEMP_BULLET_CAUSE_OF_DETONATION,
 GiCLUSTER_BOMB_BULLET_CAUSE_OF_DETONATION};

// Bullet Delays before firing again
const int GiWEAPON_DELAY[GiTOTAL_NUMBER_OF_WEAPONS_IN_GAME] = 
{GiNORMAL_WEAPON_DELAY, GiTHREE_NORMAL_WEAPON_DELAY,
 GiMACHINE_GUN_WEAPON_DELAY, GiTHREE_MACHINE_GUN_WEAPON_DELAY,
 GiFLAME_THROWER_WEAPON_DELAY, GiFIREBALL_WEAPON_DELAY,
 GiLASER_WEAPON_DELAY, GiBOMB_WEAPON_DELAY,
 GiRAM_WEAPON_DELAY, GiBUBBLE_WEAPON_DELAY,
 GiHEAT_SEEK_WEAPON_DELAY, GiMISSILE_WEAPON_DELAY,
 GiSONIC_WAVE_WEAPON_DELAY, GiEMP_WEAPON_DELAY,
 GiCLUSTER_BOMB_WEAPON_DELAY};


#endif

